jobs: 
  deploy:
    docker:
      - image: ubuntu:latest
    environment:
      - PROJECT_NAME: "daily-discussion-bot"
      - PROJECT_DESCRIPTION: "Daily Discussion bot for chicubs subreddit"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get -y -qq update
            apt-get -y install python-pip python-dev build-essential zip
            pip install awscli --upgrade
      - run:
          name: Set AWS region
          command: |
            aws configure set region "us-east-1"
            aws configure set default.region "us-east-1"
      - run:
          name: Create AWS resource group
          command: |
            RESOURCE_QUERY='{"Type":"TAG_FILTERS_1_0","Query":"{\"ResourceTypeFilters\":[\"AWS::AllSupported\"],\"TagFilters\":[{\"Key\":\"Project\",\"Values\":[\"'"${PROJECT_NAME}"'\"]}]}"}'
            {
              aws resource-groups update-group-query \
                --group-name ${PROJECT_NAME} \
                --resource-query ${RESOURCE_QUERY}
            } || {
              aws resource-groups create-group \
                --name ${PROJECT_NAME} \
                --description "${PROJECT_DESCRIPTION}" \
                --resource-query ${RESOURCE_QUERY}
            }
      - run:
          name: Create ElastiCache instance
          command: |
            aws elasticache create-cache-cluster \
              --cache-cluster-id "${PROJECT_NAME}" \
              --engine redis \
              --az-mode single-az \
              --preferred-availability-zone us-east-1 \
              --cache-node-type cache.t2.micro \
              --tags Key=Project,Value=${PROJECT_NAME}
      - run:
          name: Deploy Lambda function
          command: |
            rm -rf .deploy
            mkdir .deploy
            pip install -r requirements.txt -t .deploy
            echo -e "[install]\nprefix=" > .deploy/setup.cfg
            cp -rf src/* .deploy
            cd .deploy
            zip -r deploy.zip .
            ZIP_FILE_PATH="fileb://deploy.zip"
            {
              aws lambda create-function \
                --function-name ${PROJECT_NAME} \
                --role ${LAMBDA_ROLE_ARN} \
                --handler lambda.handler \
                --runtime python2.7 \
                --tags Project=${PROJECT_NAME} \
                --zip-file "${ZIP_FILE_PATH}" \
                --publish
            } || {
              aws lambda update-function-code \
                --function-name ${PROJECT_NAME} \
                --zip-file "${ZIP_FILE_PATH}"
            }

workflows:
  version: 2
  deploy: 
    jobs:
      - deploy:
          context: AWS