jobs: 
  deploy:
    docker:
      - image: ubuntu:latest
    environment:
      - PROJECT_NAME: "daily-discussion-bot"
      - PROJECT_DESCRIPTION: "Daily Discussion bot for chicubs subreddit"
    steps:
      - checkout
      - run:
          name: Deploy
          command: chmod +x .circleci/deploy.sh && ./.circleci/deploy.sh

workflows:
  version: 2
  deploy: 
    jobs:
      - deploy:
          context: AWS