jobs: 
  deploy:
    docker:
      - image: ubuntu:latest
    environment:
      - PROJECT_NAME: "daily-discussion-bot"
      - PROJECT_DESCRIPTION: "Daily Discussion bot for chicubs subreddit"
    steps:
      - checkout
      - run:
          name: CHMOD
          command: chmod +x .circleci/*.sh
      - run:
          name: Install AWS CLI dependencies
          command: ./.circleci/install_dependencies.sh
      - run:
          name: Create AWS resource group
          command: ./.circleci/create_resource_group.sh
      - run:
          name: Deploy to Lambda
          command: ./.circleci/deploy_to_lambda.sh

workflows:
  version: 2
  deploy: 
    jobs:
      - deploy:
          context: AWS